version: "2.4"
x-log: &default-log
  options:
    max-size: "10m"
    max-file: "3"
services:
  etcd1:
    image: docker.io/bitnami/etcd:3.5.1
    logging:
      options:
        max-file: 3
        max-size: 10m
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCDCTL_API=3
    ports:
      - 12379:2379
      - 12380:2380
    volumes:
      - ./data:/bitnami/etcd